from abc import ABC, abstractmethod

class BaseStrategy(ABC):
    def __init__(self, name):
        self.name = name

    @abstractmethod
    def generate_signals(self, market_data):
        """
        Generates trading signals (buy, sell, hold) based on market data.
        :param market_data: Dictionary or object containing market data (e.g., historical bars, real-time quotes).
        :return: A dictionary of signals, e.g., {
            'symbol': 'SPY',
            'signal': 'buy', # 'buy', 'sell', or 'hold'
            'confidence': 0.7, # A float between 0 and 1 indicating confidence
            'entry_price': 100.0 # The price at which the signal was generated
        } or None if no signal.
        """
        pass

    @abstractmethod
    def execute_trade(self, signal, trading_client, equity_risk_percent, stop_loss_percent, take_profit_percent, max_buying_power_utilization_percent):
        """
        Executes a trade based on the generated signal and risk management parameters.
        :param signal: The signal generated by generate_signals.
        :param trading_client: An instance of Alpaca's TradingClient.
        :param equity_risk_percent: Percentage of total equity to risk per trade.
        :param stop_loss_percent: Percentage drop from entry price to trigger stop-loss.
        :param take_profit_percent: Percentage gain from entry price to trigger take-profit.
        :param max_buying_power_utilization_percent: Max percentage of buying power to use for a single trade.
        """
        pass
